### ISSUE TITLE
maxCharPerLine fails on tilde-prefixed multiline variables

### ISSUE THREAD

**Issue by shooftie** [lesshint/lesshint#487] opened 2018-08-01 14:19 UTC
**Which version of `lesshint` are you using?**
5.1.0

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**
CLI & Gulp plugin

**What's your `.lesshintrc` configuration?**

```yaml
maxCharPerLine:
  enabled: true
  limit: 80
```

**If you're reporting a bug, please show us some code that's failing.**

```less
// lesshint-disable maxCharPerLine
@media-md-retina:  ~'only screen and (-webkit-min-device-pixel-ratio: 1.5)     and @{media-md-part},
                     only screen and (   min--moz-device-pixel-ratio: 1.5)     and @{media-md-part},
                     only screen and (     -o-min-device-pixel-ratio: 3/2)     and @{media-md-part},
                     only screen and (        min-device-pixel-ratio: 1.5)     and @{media-md-part},
                     only screen and (                min-resolution: 144dpi)  and @{media-md-part},
                     only screen and (                min-resolution: 1.5dppx) and @{media-md-part}';
// lesshint-enable maxCharPerLine
```

**What did you expect to happen?**
That the linting errors for `maxCharPerLine` would be suppressed for the entire block

**What's the actual result?**
```
Warning: _media-queries.less: line 21, maxCharPerLine: Line should not exceed 80 characters, 100 found.
Warning: _media-queries.less: line 21, maxCharPerLine: Line should not exceed 80 characters, 100 found.
Warning: _media-queries.less: line 22, maxCharPerLine: Line should not exceed 80 characters, 100 found.
Warning: _media-queries.less: line 22, maxCharPerLine: Line should not exceed 80 characters, 100 found.
Warning: _media-queries.less: line 23, maxCharPerLine: Line should not exceed 80 characters, 100 found.
Warning: _media-queries.less: line 23, maxCharPerLine: Line should not exceed 80 characters, 100 found.
Warning: _media-queries.less: line 24, maxCharPerLine: Line should not exceed 80 characters, 101 found.
Warning: _media-queries.less: line 24, maxCharPerLine: Line should not exceed 80 characters, 101 found.
```
**Would you be interested in submitting a PR for this issue?**
Unfortunately that would beyond my abilities.

**Comment by jwilsson** [comment] 2018-08-07 17:12
Hi!
Sorry for the delay, I've been out of town.

However, I can confirm this with any multiline variables and it seems to be an issue with our [Less parser](https://github.com/shellscape/postcss-less/). I'll file an issue over there.

**Comment by jwilsson** [comment] 2018-12-19 18:10
This should be fixed with a new version of our Less parser in `6.0.0`.

**Closed by jwilsson** 2018-12-19 18:10 UTC
Labels: blocked, bug, linter
