### ISSUE TITLE
Feature request: mixins should be at top of blocks

### ISSUE THREAD

**Issue by adam-lynch** [lesshint/lesshint#125] opened 2016-02-13 22:37 UTC
Invalid:

```less
.a {
  color: red;
  .something();
}
```

Valid:

```less
.a {
  .something();
  color: red;
}
```

(Ideally I want a newline after them too but I won't ask for too much :smile: )

**Comment by jwilsson** [comment] 2016-02-14 13:30
Sounds like a duplicate of #90, please reopen if you disagree :)

**Closed by jwilsson** 2016-02-14 13:30 UTC
