### ISSUE TITLE
qualifyingElement should allow `&`

### ISSUE THREAD

**Issue by adam-lynch** [lesshint/lesshint#131] opened 2016-02-13 23:25 UTC
This fails:

```less
.button-base(
  @baseBackgroundColour,
  @focusBackgroundColor: @baseBackgroundColour,
  @hoverBackgroundColour: lighten(@baseBackgroundColour, @buttonBackgroundDelta),
  @activeBackgroundColour: darken(@baseBackgroundColour, @buttonBackgroundDelta)
) {
  // ...
  &[disabled] {
    background: gray;
  }
  // ...
}
```

**Comment by jwilsson** [comment] 2016-02-14 13:39
This sounds like a duplicate of #118, please reopen if you disagree :)

**Closed by jwilsson** 2016-02-14 13:39 UTC
