### ISSUE TITLE
Picking up incorrect depth when max depthLevel specified

### ISSUE THREAD

**Issue by JakeSidSmith** [lesshint/lesshint#370] opened 2017-03-29 17:22 UTC
**Which version of `lesshint` are you using?**

3.1.1

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**

CLI

```
lesshint less/
```

**What's your `.lesshintrc` configuration?**

```json
{
  "fileExtensions": [
    ".less",
    ".css"
  ],
  "excludedFiles": [
    "fonts.less"
  ],
  "attributeQuotes": {
    "enabled": true,
    "severity": "error"
  },
  "borderZero": {
    "enabled": true,
    "severity": "error",
    "style": "zero"
  },
  "comment": {
    "enabled": false,
    "severity": "error"
  },
  "decimalZero": {
    "enabled": true,
    "severity": "error",
    "style": "leading"
  },
  "depthLevel": {
    "enabled": true,
    "severity": "error",
    "depth": 3
  },
  "duplicateProperty": {
    "enabled": true,
    "severity": "error",
    "exclude": []
  },
  "emptyRule": {
    "enabled": true,
    "severity": "error"
  },
  "finalNewline": {
    "enabled": true,
    "severity": "error"
  },
  "hexLength": {
    "enabled": true,
    "severity": "error",
    "style": "long"
  },
  "hexNotation": {
    "enabled": true,
    "severity": "error",
    "style": "uppercase"
  },
  "hexValidation": {
    "enabled": true,
    "severity": "error"
  },
  "idSelector": {
    "enabled": true,
    "severity": "error",
    "exclude": []
  },
  "importantRule": {
    "enabled": true,
    "severity": "error"
  },
  "importPath": {
    "enabled": true,
    "severity": "error",
    "filenameExtension": true,
    "leadingUnderscore": false,
    "exclude": []
  },
  "maxCharPerLine": {
    "enabled": true,
    "severity": "error",
    "limit": 120
  },
  "newlineAfterBlock": {
    "enabled": true,
    "severity": "error"
  },
  "propertyOrdering": {
    "enabled": false,
    "severity": "error",
    "style": "alpha"
  },
  "propertyUnits": {
    "enabled": false,
    "severity": "error",
    "valid": ["px"],
    "invalid": ["pt"],
    "properties": {
      "line-height": []
    }
  },
  "qualifyingElement": {
    "enabled": true,
    "severity": "error",
    "allowWithAttribute": false,
    "allowWithClass": false,
    "allowWithId": false
  },
  "selectorNaming": {
    "enabled": true,
    "severity": "error",
    "disallowUppercase": true,
    "disallowUnderscore": true,
    "disallowDash": false,
    "exclude": []
  },
  "singleLinePerProperty": {
    "enabled": true,
    "severity": "error",
    "allowSingleLineRules": false
  },
  "singleLinePerSelector": {
    "enabled": true,
    "severity": "error",
    "style": "none"
  },
  "spaceAfterPropertyColon": {
    "enabled": true,
    "severity": "error",
    "style": "one_space"
  },
  "spaceAfterPropertyName": {
    "enabled": true,
    "severity": "error",
    "style": "no_space"
  },
  "spaceAfterPropertyValue": {
    "enabled": true,
    "severity": "error",
    "style": "no_space"
  },
  "spaceAroundComma": {
    "enabled": true,
    "severity": "error",
    "allowNewline": false,
    "style": "after"
  },
  "spaceAroundOperator": {
    "enabled": true,
    "severity": "error",
    "style": "both"
  },
  "spaceBeforeBrace": {
    "enabled": true,
    "severity": "error",
    "style": "one_space"
  },
  "spaceBetweenParens": {
    "enabled": true,
    "severity": "error",
    "style": "no_space"
  },
  "stringQuotes": {
    "enabled": true,
    "severity": "error",
    "style": "single"
  },
  "trailingSemicolon": {
    "enabled": true,
    "severity": "error"
  },
  "trailingWhitespace": {
    "enabled": true,
    "severity": "error"
  },
  "universalSelector": {
    "enabled": true,
    "severity": "error"
  },
  "urlFormat": {
    "enabled": false,
    "severity": "error",
    "style": "relative"
  },
  "urlQuotes": {
    "enabled": true,
    "severity": "error"
  },
  "variableValue": {
    "enabled": true,
    "severity": "error",
    "always": [
      "color",
      "background",
      "backgorund-color",
      "border",
      "border-color",
      "box-shadow",
      "fill",
      "stroke",
      "filter"
    ]
  },
  "zeroUnit": {
    "enabled": true,
    "severity": "error",
    "style": "no_unit"
  }
}
```

**If you're reporting a bug, please show us some code that's failing.**

Only seems to fail if there's more than one mixin. But also having lots of other depth issues all over the less.

```less
.row {
  .youtube-container {
    .col(12);
    .col-small(8);
    .col-medium(6);
  }
}
```

Also here:

```less
.blog-post-info {
  list-style: none;
  margin: 0;
  padding: 0;

  li {
    margin: @block-spacing / 2 0;

    &:first-child {
      margin-top: @block-spacing;
    }

    &:last-child {
      margin-bottom: @block-spacing;
    }
  }
}
```

**What did you expect to happen?**

This to pass (as it is only 3 deep).

**What's the actual result?**

```shell
Error: blog.less: line 1, col 1, depthLevel: There shouldn't be more than '3' levels deep from the style's parent, check the children's depth.
Error: blog.less: line 2, col 3, depthLevel: There shouldn't be more than '3' levels deep from the style's parent, check the children's depth.
```

**Would you be interested in submitting a PR for this issue?**

I guess. I wouldn't know where to start...

**Comment by jwilsson** [comment] 2017-03-29 19:03
Confirmed, thanks for the report!

If you are interested in submitting a PR, we'd be happy to help! Start by checking out the [contributing guidelines](https://github.com/lesshint/lesshint/blob/master/CONTRIBUTING.md).

After that, I'd start looking at these lines in `lib/linters/depth_level.js`:

```js
node.walkRules(() => {
    levels++;
});
```

And the PostCSS docs on [walkRules](http://api.postcss.org/Container.html#walkRules) should be helpful too. Again, just give us a shout if you need any help.

**Comment by JakeSidSmith** [comment] 2017-04-04 10:02
@jwilsson, thanks for the info. Trying to find some time to take a look at this. :)

**Comment by JakeSidSmith** [comment] 2017-04-10 10:13
@jwilsson not sure how to approach this...

I'm not sure this is really possible with the PostCSS walker, unless there's a plugin that make it work properly. It picks up mixins as regular "rules", and I think the only way to tell the difference would be to regex match the selectors, but when they contain a block, it appears not to traverse that block, which means it wont lint anything inside there.

E.g.

```javascript
selector: '.foo-mixin-3({ .mixin-3(); width: 100%; })',
```

Two issues here:

1. How do we tell the difference between a rule selector, and a mixin (bare in mind that mixins can be defined in many different ways, examples below).
2. Walker does not appear to traverse blocks inside mixins.

```less
.mixin() {
  color: red;
}

.selector {
  .mixin;
  .mixin();
  .mixin(argument);
  .mixin(argument, argument);
  .mixin(argument, argument;);
  .mixin({
    content: 'block';
  });
}
```

**Comment by JakeSidSmith** [comment] 2017-04-10 13:55
An [issue](https://github.com/webschik/postcss-less/issues/63) in `postcss-less` mentions the lack of mixin parsing, and a fix is available [here](https://github.com/webschik/postcss-less/pull/65). I think I'll have to wait for that.

Though, `postcss-less` appears to be in need of maintainers. Perhaps you guys would like to take it on?

**Comment by shellscape** [comment] 2017-04-10 14:56
yeah their project was put together for a specific integration, and I don't think the owner was prepared for the adopting and wide use it got. slow movement has kind of been a historical problem with parsers in general (and a big reason why we switched to a postcss-based implementation). I've got three open issues of my own on that project and they haven't been addressed since August of last year.

it could be forked to the lesshint org, but maintaining parsers is hard work (postcss-values-parser has been a massive time drain because of the nuances of parsing). we'd need someone on board that'd be willing to give it attention, at least in the near term.

**Comment by JakeSidSmith** [comment] 2017-04-11 09:59
I'd fork it myself... but I've already got too many libs to maintain, and I'd only be using it for this project. I'd be happy to help out when I can if lesshint is willing to adopt that project.

Have any of you considered / tried writing your own parser for this, for your specific needs, rather than relying on a CSS parser with plugins?

**Comment by shellscape** [comment] 2017-04-11 12:40
lesshint used to rely on gonzales-pe, which was a long-established stand-alone parser that just fell into stagnation and started suffering from poor support for LESS after some questionable updates. Parsers are hard. PostCSS is really solid and made the most sense for a base.

**Comment by jwilsson** [comment] 2017-05-08 17:00
@JakeSidSmith I tried again with the code you posted (@shellscape has adopted the `postcss-less` library and started publishing fixes) and it seems to work with the latest version of it.

I'm gonna close this issue, but just leave a comment if your issue still persists!

**Closed by jwilsson** 2017-05-08 17:00 UTC
Labels: blocked, bug, linter

**Comment by JakeSidSmith** [comment] 2017-05-12 09:20
@jwilsson so, this issue should be fixed now? I'll give it a go today.

**Comment by jwilsson** [comment] 2017-05-12 10:09
@JakeSidSmith Yeah, try with the latest `lesshint`. Sorry that I wasn't clear.

**Comment by JakeSidSmith** [comment] 2017-05-20 22:46
@jwilsson you're gonna have to reopen this issue. Just updated the project that the code above is from to lesshint `3.3.1` and still having the depth issues. Only occurring with nested mixins as before.

With `depthLevel: 3`:

```less
.level-1 {
  .level-2 {
    .mixin(1); // Causes error
  }
}
```

Also, still not traversing mixin content. E.g. the following with `variableValue: 'color'` does not error:

```less
.class {
  .mixin({
    color: red; // Should error
  });
}
```
