### ISSUE TITLE
Feature request: empty line between blocks

### ISSUE THREAD

**Issue by adam-lynch** [lesshint/lesshint#126] opened 2016-02-13 22:41 UTC
Invalid:

```less
.a {
  color: red;
}
.b {
  color: blue;
}
```

Valid:

```less
.a {
  color: red;
}

.b {
  color: blue;
}
```

**Comment by jwilsson** [comment] 2016-02-14 13:31
Sounds like a duplicate of #116, please reopen if you disagree :)

**Closed by jwilsson** 2016-02-14 13:31 UTC

**Comment by adam-lynch** [comment] 2016-02-14 13:53
Sorry for missing these :)


Regards,
Adam Lynch
