### ISSUE TITLE
spaceAroundOperator and box-shadow

### ISSUE THREAD

**Issue by wareczek** [lesshint/lesshint#141] opened 2016-02-21 13:56 UTC
`box-shadow: 1px 1px 1px -1px rgba(0, 0, 0, .75);`

throws error:
> Operators should be preceded and followed by one space.

**Comment by jwilsson** [comment] 2016-02-21 15:19
This sounds like a duplicate of #124, please reopen if you disagree :)

**Closed by jwilsson** 2016-02-21 15:19 UTC
