### ISSUE TITLE
Evaluating PostCSS-LESS

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#151] opened 2016-03-07 14:01 UTC
I'm opening this one because I think it may be time. https://github.com/webschik/postcss-less has made much more progress in recent months than I've been able to (because I haven't been able to at all) on the gilt PostCSS-LESS version. Initially the two projects were virtually identical anyhow. @webschik seems to have made some solid additions, and I think it's time we start to evaluate this as an option using a few of our simplest linters and tests.

I was thinking that starting with one would be good, and expanding from there. What I don't know is which linter(s) we should start with. So I'd like to request some help in setting up a roadmap of sorts for which linter(s) go first.

If we gather a list of what isn't working correctly, we'll be able to effectively contribute or patch a fork. I'm about to have a wealth of time available and I'd like to knock this one out.

**Comment by kokarn** [comment] 2016-03-07 14:27
With all the bad pr i've heard of gonzales-pe i'd really like this to be done. 
Has anyone talked to @webschik? 
Would be nice to hear what he has to say and if we can work together on that.

My thinking is that we should start with the most complex linters and fix any errors that might pop up there and then work "backwards" with the more straighforward ones. That way we get alerted really fast to stuff that's not working as intended, and if we are on a good path.

**Comment by shellscape** [comment] 2016-03-07 15:50
I'm more of a fan of the low-hanging-fruit approach, as it's less time intensive and more progress can be made (in theory). There's going to be a lot of setup required to shift the linters and the module base to postcss-less, and adding the time it takes to debug the more complex linters doesn't sound appetizing to me personally, to kick off that effort :) if you'd like to once we've got a base in place, I'll have no objections. But I'd prefer some simpler targets initially.

**Comment by webschik** [comment] 2016-03-07 19:54
Hi guys! 
I'm using my parser with [Stylelint](https://github.com/stylelint/stylelint), but in some tricky way. [There is](https://github.com/stylelint/stylelint/issues/810) a discussion about implementation of  `postcss-less` in Stylelint. 

If you want to test my parser with `lesshint` - no problem, I will try to help you and fix some possible issues.

**Comment by kokarn** [comment] 2016-03-08 08:54
Sounds great @webschik!
@shellscape if that's how you feel, then let's go with that unless @jwilsson has some major objections.

**Comment by jwilsson** [comment] 2016-03-08 09:41
I don't have any particular preference on how to do it and @shellscape, if you wanna take the lead on this go for it :) I'm pretty swamped this week but I'll hopefully be able to take a closer look at the PostCSS API and some rules over the weekend or next week.

Some rules off the top of my head that should be easy to start out with:
`borderZero`
`comment`
`emptyRule` 
`idSelector`
`importantRule`
`spaceBeforeBrace`

**Comment by shellscape** [comment] 2016-03-08 13:35
:+1:  everyone. I'll start on work at some point this week.

**Comment by jwilsson** [comment] 2016-03-13 20:48
I've just pushed a first WIP to the `postcss-less-parser-replacement` branch. I've also converted `borderZero` to use `postcss-less` instead. I'm not 100% satisfied with the looks of `linter.js` but it's a start. A later issue is how much public API breakage we want to introduce, some is inevitable but I'll post a bigger meta-issue about things we can do in a `2.0.0` later.

But the important thing right now is this base, so we're able to continue working on the other linters. And we've obviously got some huge test failures on everything else. I'd also like to request some help with figuring out a nice, clean way of reporting the correct result columns since that doesn't work in the same way anymore.

**Comment by shellscape** [comment] 2016-03-14 12:19
You're a machine. We may be able to get something into PostCSS for the columns. I'll have a look when I get on this.

**Comment by shellscape** [comment] 2016-03-14 19:37
After watching https://github.com/webschik/postcss-less/pull/12 I'm a little more hesitant to run with webshik's effort. That PR adds a massive amount of cruft to the repo, and it gives me the willies. I'm gonna keep poking at the Gilt effort and cherry pick the updates/improvements that the PR contains with regard to the actual syntax, keeping the repo clean and tidy.

**Comment by jwilsson** [comment] 2016-03-21 14:51
Closing this in favor of #158 since we've started work on this.

**Closed by jwilsson** 2016-03-21 14:51 UTC
