### ISSUE TITLE
SpaceBeforeBrace New Line

### ISSUE THREAD

**Issue by crash-dive** [lesshint/lesshint#244] opened 2016-08-23 20:09 UTC
I think there is a bug in the reg ex here: https://github.com/lesshint/lesshint/blob/77a502cb25dd8e8368b9a35aaabd183352d6c03e/lib/linters/space_before_brace.js#L15

It does not allow for whitespace between the selector and the brace so this is allowed

```css
ul
{
//Some Styles
li
{
//Some Styles
}
}
```

But this is not because between li and { there are 4 spaces.
```css
ul
{
    //Some Styles

    li
    {
        //Some Styles
    }
}
```

I think the fix would be to change the regex to /^\n *\t*$/ which would require a return directly after the selector but also allow for tabs or a spaces used to indent the code.

I do not think this is intended behaviour and I am happy to send a pull request but but fixing it would be a breaking change.

**Comment by jwilsson** [comment] 2016-08-29 08:37
Hi,
Thanks for the report!

I agree that this isn't the expected behaviour but it's also, as you say, tricky since it can be considered a breaking change but on the other hand I think it's a bug. 

What are your thoughts, @kokarn and @shellscape?

**Comment by kokarn** [comment] 2016-08-29 11:05
I'd call it a bug that should be fixed. 
Indentation is maybe something we need to look into in other places as well where we match whitespace and/or newline?

**Comment by jwilsson** [comment] 2016-09-09 09:25
Sorry for not getting back sooner. After some more thinking I say it's a bug. @crash-dive are you still interested in sending a PR?

**Comment by crash-dive** [comment] 2016-09-09 17:09
@jwilsson I have sent a PR. There is also another related fix in it related to the incorrect usage of \s in the reg ex.

**Closed** 2016-09-11 18:26 UTC
