### ISSUE TITLE
zeroUnit is incorrectly applied to opacity

### ISSUE THREAD

**Issue by ajaswa** [lesshint/lesshint#152] opened 2016-03-15 17:40 UTC
According to the spec, the `opacity` property does not have a unit for its value. When running lesshint against a less file with `opacity` properties, the `Unit should not be omitted on zero values.` warning comes up.

Reference docs:
https://www.w3.org/wiki/CSS/Properties/opacity
https://www.w3.org/TR/css3-color/#transparency
https://developer.mozilla.org/en-US/docs/Web/CSS/opacity

**Comment by jwilsson** [comment] 2016-03-15 19:05
Confirmed. I'm guessing from our Twitter conversation that you're interested in patching it?

I can't come up with any other properties which works like `opacity` right now, but if you do please add them here too!

**Comment by ajaswa** [comment] 2016-03-15 19:11
Indeed, I'd like to take a stab at it. I can't come up with anything else either. If I do I'll include them here.

**Comment by ajaswa** [comment] 2016-03-15 22:27
z-index also has a non-unit numerical value.

https://developer.mozilla.org/en-US/docs/Web/CSS/z-index

**Comment by kokarn** [comment] 2016-03-16 15:54
How about other things? 
It's recommended to use line-height without a unit for better scaling, but it's possible to use with units.

**Comment by shellscape** [comment] 2016-03-16 17:17
Sounds like there needs to be a property exclusion list for this one.

**Comment by ajaswa** [comment] 2016-03-16 17:25
@shellscape indeed. I added an array of properties that can be easily added to when more properties are "discovered" that have non-unit values. Though I'm not sure I've done it in the right place but it seems to work.

Right now the list includes `opacity`, `z-index' and `line-height`.

**Comment by jwilsson** [comment] 2016-03-18 13:12
@shellscape were you thinking a configurable list or a hardcoded one? I'm fine with either.

**Comment by shellscape** [comment] 2016-03-18 17:28
following previous patterns, a configurable list with defaults seems to be a good idea.

**Comment by ajaswa** [comment] 2016-03-18 17:39
I disagree. Allowing users/devs to configure a list of properties to determine what the CSS spec has already defined seems like a very bad idea. If thats not the case then why not have all the units configureable?

**Comment by shellscape** [comment] 2016-03-18 17:52
@ajaswa lesshint linters follow a pattern of configurability. I don't quite get what "all the units" means in this context, but allowing users to add properties to that list the spec already defines is certainly reasonable.

**Comment by ajaswa** [comment] 2016-03-18 17:55
What I mean by "all the units" is that by your logic this line should also be set in configuration: https://github.com/lesshint/lesshint/blob/master/lib/linters/zero_unit.js#L12

**Comment by shellscape** [comment] 2016-03-18 19:18
Sure, I would consider the ability to add units to that list to also be reasonable. This would have impact in preprocessors, allow users to expand upon lesshint if it were to fall out of sync with the spec, etc.

**Comment by jwilsson** [comment] 2016-03-19 10:12
I'm sorry to see that #153 was closed and deleted, and for missing the discussion but my two cents on this is:

* In `zeroUnit`, we keep a list of properties defined without values in the CSS spec (i.e. `opacity` and `z-index`). And add a `exclude` option which is merged with the default, hardcoded ones. So no one's able to remove things in the CSS spec but add something if, for example someone wants to exclude `padding` for whatever reason.
* I don't think `line-height` needs to be included in the defaults, though. It's a bit too opinonated and frankly, `line-height: 0` doesn't make much sense to me ;)
* I don't know what my opinion on excluding properties is, though. Perhaps we should keep that discussion in another issue?

What are you guys thoughts on this? @ajaswa @shellscape

**Comment by jwilsson** [comment] 2016-03-19 10:17
Sorry @shellscape, didn't see your PR before posting.

**Comment by shellscape** [comment] 2016-03-19 13:29
I'm gonna close this one since @ajaswa has vanished. can continue discussion on #156.

**Closed by shellscape** 2016-03-19 13:29 UTC
Labels: bug, linter
