### ISSUE TITLE
spaceBetweenParens reports incorrect line numbers

### ISSUE THREAD

**Issue by Kolyunya** [lesshint/lesshint#241] opened 2016-08-19 07:09 UTC
The following warnings are reported while processing the following file:
```less
.item {
    &_enabled {
        color: rgb( 42, 42, 42 );
    }
}
```

```bash
Warning: test.less: line 1, col 20, spaceBetweenParens: Opening parenthesis should not be followed by any space.
Warning: test.less: line 1, col 31, spaceBetweenParens: Closing parenthesis should not be preceded by any space.
```

Reported line numbers are incorrect.

**Comment by kokarn** [comment] 2016-08-19 07:10
This is probably a duplicate of #231 but will keep open for consistency.

**Comment by Kolyunya** [comment] 2016-08-19 07:13
@kokarn #231 is about selectors while this one is about properties. #231 may be even considered as expected behavior while this can not.

**Comment by jwilsson** [comment] 2016-08-19 07:56
Agreed, this is a different bug.

**Comment by kokarn** [comment] 2016-08-19 08:19
Good thing I kept it open then and good catch by you guys :dancer:

**Closed** 2016-08-31 06:17 UTC
Labels: bug, linter
